HEADERS_FORJA_INGESTA = [
    "ORDEN_ID",
    "N° Orden",
    "Tipo de Documento",
    "N° de Documento",
    "Nit Empresa",
    "DX codigo",
    "Nombre de Medicamento",
    "Cantidad",
    "Posología",
    "TiempoDeTratamiento en dias",
    "Fecha de la cita AAAAMMDD",
    "VIGENCIA_HASTA",
    "N° de contacto paciente",
    "FECHA_PROCESO",
    "fecha de la admision",
    "LINK_PDF",
    "LINK_CORREO",
    "RUTA_CARPETA",
    "ESTADO_ORDEN",
    "CAUSAL_ORDEN",
    "ALERTA_ITEM",
    "ALERTA_LOGICA",
    "OMISION_FILAS_PDF",
    "Admision",
    "ASIGNACION",
    "DERECHOS_ESTADO",
    "DERECHOS_PROGRAMA_EPS",
    "DERECHOS_EMAIL",
    "DERECHOS_PLAN_AUTORIZACION",
    "DERECHOS_DESCRIPCION_PROGRAMA",
    "DERECHOS_TIPOUSUARIO",
    "DERECHOS_COBERTURA",
    "ESTADO AUTOGESTION",
    "OBSERVACIONES",
    "AUTORIZACION",
    "Código medicamento",
    "FECHA DE MALLA",
    "FECHA ASIGNACION",
    "FECHA DE AUTORIZACION",
    "FECHA DISPENSACION",
    "HOMOLOGACION",
    "ESTADO FARMACIA",
    "FECHA DISPENSADO",
    "FECHA_MED_PENDIENTE",
    "FECHA_DEV_AUTORIZACIONES"
    # "ARCHIVO_ORIGEN",
    # "FORMULA_ID",
    # "MEDICAMENTO_ID"
]
